### ISSUE TITLE
A seleção dos posts é feita sem critério de fim / começo de palavra

### ISSUE THREAD

**Issue by soultobleed** [tiago-pereira/brasil-on-reddit#1]
Hoje os posts são capturados pelas tags dispostas em EXPRESSIONS_TO_MONITOR. Para o brasil-on-reddit essas tags estão configuradas como brasil e brazil, o que nos trás alguns falsos positivos (exemplo https://www.reddit.com/r/The_Donald/comments/6crwfl/donna_brazile_was_the_dnc_official_seth_had/) 

**brazil**e nesse caso é taggeado pelo bot.

**Comment by tiago-pereira** [comment]
A ideia é essa mesmo, assim pegamos também "brazilians", "brasileiros" e algumas línguas onde Brasil é escrito um pouco diferente. "Brasilien" é Brasil em alemão, por exemplo.
Claro que tem algumas que não pegamos,  tipo "Brésil" em francês e línguas que possuem outro alfabeto.

Não consigo pensar em uma solução definitiva pra esse problema, talvez adicionar uma lista de exceções?
Adicionar combinações de palavras que abortam a postagem, tipo "brazile e donna".

**Comment by soultobleed** [comment]
Estou tentando fazer por regex, veja o que acha: 
![image](https://cloud.githubusercontent.com/assets/2480975/26361541/b4e2ec06-3fb1-11e7-9025-bab1e7d1a369.png)

dentro do bot.py já está implementado com o regex, só falta conseguir algum(as) combinações para atender (quase) tudo. 

Acho que preciso de uma mão nos edge cases e em algumas outras línguas que a grafia é diferente.

**Comment by tiago-pereira** [comment]
Acho bem válido, o problema é só verificar todas as grafias mesmo. Sem falar que caso alguma delas seja sinônima de outra, não tem muito o que fazer (se Brazile for realmente Brasil em alguma língua, por exemplo).

**Comment by tiago-pereira** [comment]
Adicionado blacklist.
