### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by celioware** [tiago-pereira/brasil-on-reddit#3]
Criar uma validação do post com base na combinação de palavras.

```
BLACKLIST = ( ("trump", "brazile") )
```

este BLACKLIST poderia ser utilizado para evitar que o bot fique replicando algum determinado conteúdo, thread, ou pessoas indesejadas (Banidas)

**Comment by tiago-pereira** [comment]
Valeu Skalldihor. Usei um mix daquelas nossas ideias. Usei as listas simples pra ficar igual ao resto da config.
